language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

#env:
#    - PLATFORMIO_CI_SRC=ESPController/src/main.cpp:./ESPController/include:./ESPController/lib/crc16:./ESPController/lib/settings:./ESPController/lib/ticker
#    ESPController/lib/crc16 ESPController/lib/settings ESPController/lib/ticker

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run --project-dir=./ATTINYCellModule  --project-conf=./ATTINYCellModule/platformio.ini
    - platformio run --project-dir=./ATTINYCellModuleTestPrg  --project-conf=./ATTINYCellModuleTestPrg/platformio.ini
    - platformio run --project-dir=./ATTINYPIDTuning  --project-conf=./ATTINYPIDTuning/platformio.ini
    - platformio run --project-dir=./ESPController  --project-conf=./ESPController/platformio.ini
